### ISSUE TITLE
rdflib version lock removal

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/databaker-docker#16]
Version of rdlib is locked at 4.2.2. Version 5.0 was released April 2020. There are some breaking changes. https://github.com/RDFLib/rdflib/releases, details at https://github.com/RDFLib/rdflib/blob/master/docs/upgrade4to5.rst.

**Comment by ajtucker** [comment]
See GSS-Cogs/gss-utils#49. StatsWales puts metadata as RDFa on their pages, but the RDFa parser wasn't updated in rdflib v5.

**Comment by canwaf** [comment]
Unpinned.
